version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.0
    working_directory: /go/src/github.com/ks888/goobj
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...  
